# Estágio 1: Construir a imagem com as dependências Node.js
FROM node:latest AS build
WORKDIR /app
COPY ./app/package*.json ./
RUN npm install

# Estágio 2: Copiar os arquivos e configurar o ambiente de produção
FROM node:alpine
WORKDIR /app

# Copiar node_modules do estágio de construção para a imagem final
COPY --from=build /app/node_modules ./node_modules

# Copiar os outros arquivos necessários
COPY ./app .
EXPOSE 3000
CMD ["node", "app.js"]