# Use uma imagem oficial do Node.js como base
FROM node:latest

# Crie e defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo package.json e o package-lock.json (se existirem) para o diretório de trabalho
COPY ./app/package*.json ./
COPY ./app/app.js ./

# Instale as dependências do projeto
RUN npm install

# Exponha a porta em que o aplicativo irá escutar
EXPOSE 3000

# Comando para iniciar a aplicação (ajuste conforme necessário)
CMD ["node", "app.js"]