version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
    networks:
      - fullcycle

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    working_dir: /app
    command: node app.js
    environment:
      NODE_ENV: production
    networks:
      - fullcycle
    depends_on:
      - postgres
    

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
    networks:
      - fullcycle

networks:
  fullcycle:
    driver: bridge