# Use a imagem oficial do Nginx como base
FROM nginx:latest

# Copie o arquivo de configuração personalizado para o diretório de configuração do Nginx
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Copie os arquivos do site para o diretório padrão do Nginx
#COPY ./site /usr/share/nginx/html

# Exponha a porta 80
EXPOSE 80